//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SastaServicesDBEntities : DbContext
    {
        public SastaServicesDBEntities()
            : base("name=SastaServicesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STPBanner> STPBanners { get; set; }
        public virtual DbSet<STPBannerOffer> STPBannerOffers { get; set; }
        public virtual DbSet<STPOrder> STPOrders { get; set; }
        public virtual DbSet<STPPrefferedTime> STPPrefferedTimes { get; set; }
        public virtual DbSet<STPProductBrand> STPProductBrands { get; set; }
        public virtual DbSet<STPProductItem> STPProductItems { get; set; }
        public virtual DbSet<STPProductType> STPProductTypes { get; set; }
        public virtual DbSet<STPQuickCall> STPQuickCalls { get; set; }
        public virtual DbSet<STPService> STPServices { get; set; }
        public virtual DbSet<STPServicesFuelType> STPServicesFuelTypes { get; set; }
        public virtual DbSet<STPServicesUnitType> STPServicesUnitTypes { get; set; }
        public virtual DbSet<STPServiceType> STPServiceTypes { get; set; }
        public virtual DbSet<STPStatu> STPStatus { get; set; }
        public virtual DbSet<STPStatusType> STPStatusTypes { get; set; }
        public virtual DbSet<StpUser> StpUsers { get; set; }
        public virtual DbSet<StpUserType> StpUserTypes { get; set; }
        public virtual DbSet<TRNCustomerOrder> TRNCustomerOrders { get; set; }
        public virtual DbSet<TRNInvoice> TRNInvoices { get; set; }
        public virtual DbSet<TRNSubscription> TRNSubscriptions { get; set; }
    
        public virtual ObjectResult<ReportInvoice_Result> ReportInvoice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportInvoice_Result>("ReportInvoice");
        }
    }
}
