//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPBannerOffer
    {
        public int ID { get; set; }
        public string ShortDescriptionBefore { get; set; }
        public string MainHeading { get; set; }
        public Nullable<int> DiscoutRate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string ShortDescriptionAfter { get; set; }
        public string ImageFilePath { get; set; }
    }
}
