//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STPOrder()
        {
            this.TRNInvoices = new HashSet<TRNInvoice>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public int STPServiceTypeID { get; set; }
        public int STPServicesFuelTypesID { get; set; }
        public int STPServicesUnitTypesID { get; set; }
        public string Description { get; set; }
        public System.DateTime PrefferedDate { get; set; }
        public int PrefferedTimeID { get; set; }
        public System.DateTime createdDateTime { get; set; }
        public Nullable<int> STPStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRNInvoice> TRNInvoices { get; set; }
        public virtual STPServicesFuelType STPServicesFuelType { get; set; }
        public virtual STPPrefferedTime STPPrefferedTime { get; set; }
        public virtual STPServiceType STPServiceType { get; set; }
        public virtual STPStatusType STPStatusType { get; set; }
        public virtual STPServicesUnitType STPServicesUnitType { get; set; }
        public virtual STPStatu STPStatu { get; set; }
    }
}
