//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPProductItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STPProductItem()
        {
            this.STPServices = new HashSet<STPService>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string ItemNo { get; set; }
        public string ProductDescription { get; set; }
        public int STPProductBrandID { get; set; }
        public bool IsAvailible { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ImageFilePath { get; set; }
        public decimal CostPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal SpecialDiscount { get; set; }
        public int FuelTypeId { get; set; }
        public int UnitTypeId { get; set; }
    
        public virtual STPProductType STPProductType { get; set; }
        public virtual STPServicesFuelType STPServicesFuelType { get; set; }
        public virtual STPServicesUnitType STPServicesUnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPService> STPServices { get; set; }
    }
}
