//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STPServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STPServiceType()
        {
            this.STPOrders = new HashSet<STPOrder>();
            this.STPServices = new HashSet<STPService>();
            this.STPServicesFuelTypes = new HashSet<STPServicesFuelType>();
            this.STPServicesFuelTypes1 = new HashSet<STPServicesFuelType>();
            this.STPServicesUnitTypes = new HashSet<STPServicesUnitType>();
            this.TRNCustomerOrders = new HashSet<TRNCustomerOrder>();
        }
    
        public int ID { get; set; }
        public string ServiceTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public bool IsAvailible { get; set; }
        public string ImageFilePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPOrder> STPOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPService> STPServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPServicesFuelType> STPServicesFuelTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPServicesFuelType> STPServicesFuelTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPServicesUnitType> STPServicesUnitTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRNCustomerOrder> TRNCustomerOrders { get; set; }
    }
}
