//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSastiServices.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRNCustomerOrder
    {
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string OrderDescription { get; set; }
        public Nullable<System.DateTime> preferredDate { get; set; }
        public Nullable<int> preferredTimeID { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<int> FuelTypeId { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    
        public virtual STPPrefferedTime STPPrefferedTime { get; set; }
        public virtual STPServicesFuelType STPServicesFuelType { get; set; }
        public virtual STPServicesUnitType STPServicesUnitType { get; set; }
        public virtual STPServiceType STPServiceType { get; set; }
        public virtual STPStatu STPStatu { get; set; }
    }
}
